### ISSUE TITLE
Tracking of notifications

### ISSUE THREAD

**Issue by adgad** [Financial-Times/next-ilyushin#121]
Plan to add a hash to URLs for anything that constitutes a notification
Prefixing with beacon so next-beacon can choose to clean up the hash after sending it on. 

e.g.
#beacon:notification:mypage
#beacon:notification:myfeed
#beacon:notification:email
#beacon:notification:chrome

@commuterjoy @wheresrhys

**Comment by wheresrhys** [comment]
Mulling this over, is `beacon` the right choice of namespace? For example, a user arrives from email, we may want to do something else with that fact in addition to sending something to beacon e.g. show some messaging. Would something like '#myft:notification:chrome', read by myft-client which in turn triggers beacon, be better?
